In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('creditcard.csv')

In [3]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
data.shape

(284807, 31)

In [5]:
set(data['Class'].values)

{0, 1}

In [6]:
array = data.values

In [7]:
array

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02, ...,
        -2.10530535e-02,  1.49620000e+02,  0.00000000e+00],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
         1.47241692e-02,  2.69000000e+00,  0.00000000e+00],
       [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
        -5.97518406e-02,  3.78660000e+02,  0.00000000e+00],
       ...,
       [ 1.72788000e+05,  1.91956501e+00, -3.01253846e-01, ...,
        -2.65608286e-02,  6.78800000e+01,  0.00000000e+00],
       [ 1.72788000e+05, -2.40440050e-01,  5.30482513e-01, ...,
         1.04532821e-01,  1.00000000e+01,  0.00000000e+00],
       [ 1.72792000e+05, -5.33412522e-01, -1.89733337e-01, ...,
         1.36489143e-02,  2.17000000e+02,  0.00000000e+00]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

X = sc.fit_transform(array[:,0:29])
X

array([[-1.99658302, -0.69424232, -0.04407492, ..., -0.39217043,
         0.33089162, -0.06378115],
       [-1.99658302,  0.60849633,  0.16117592, ...,  0.26106948,
        -0.02225568,  0.04460752],
       [-1.99656197, -0.69350046, -0.81157783, ..., -0.28844675,
        -0.13713686, -0.18102083],
       ...,
       [ 1.6419735 ,  0.98002374, -0.18243372, ..., -0.18118178,
         0.01103672, -0.0804672 ],
       [ 1.6419735 , -0.12275539,  0.32125034, ...,  1.133635  ,
         0.26960398,  0.31668678],
       [ 1.64205773, -0.27233093, -0.11489898, ..., -1.69685342,
        -0.00598394,  0.04134999]])

In [9]:
Y = array[:, 30]

In [10]:
Y

array([0., 0., 0., ..., 0., 0., 0.])

In [11]:
from sklearn.ensemble import ExtraTreesClassifier

In [12]:
model = ExtraTreesClassifier()
model.fit(X,Y)

ExtraTreesClassifier()

In [13]:
model.feature_importances_


array([0.01753921, 0.01329419, 0.01377017, 0.03353242, 0.03534734,
       0.01606613, 0.01396521, 0.02276135, 0.01323783, 0.04247881,
       0.07038003, 0.05339277, 0.13046869, 0.01312297, 0.12110932,
       0.01224164, 0.06693588, 0.12843558, 0.05127853, 0.01375265,
       0.01487726, 0.01634484, 0.0126259 , 0.00980743, 0.01308998,
       0.01080531, 0.01512622, 0.01185607, 0.01235629])

In [14]:
10,11,12,14,16

(10, 11, 12, 14, 16)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [16]:
x = data.drop(['Time','V1','V2','V3','V4','V5','V6','V7','V8',
             'V9','V13','V15','V17','V18','V19','V20','V21',
             'V22','V23','V24','V25','V26','V27','V28','Amount','Class'], axis = 1)


In [17]:
x.shape

(284807, 5)

In [18]:
x.head()

V10       V11       V12       V14       V16
0  0.090794 -0.551600 -0.617801 -0.311169 -0.470401
1 -0.166974  1.612727  1.065235 -0.143772  0.463917
2  0.207643  0.624501  0.066084 -0.165946 -2.890083
3 -0.054952 -0.226487  0.178228 -0.287924 -1.059647
4  0.753074 -0.822843  0.538196 -1.119670 -0.451449

In [19]:
y = data['Class']

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [22]:
xtrain.shape

(213605, 5)

In [23]:
xtest.shape

(71202, 5)

In [24]:
ytrain.shape

(213605,)

In [25]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(xtrain,ytrain)

LogisticRegression()

In [26]:
y_pred = classifier.predict(xtest)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
print("accuracy ",accuracy_score(ytest,y_pred))

accuracy  0.9991713715906857


In [29]:
print(data['Class'].value_counts()[0])

284315


In [30]:
print(data['Class'].value_counts()[1])

492
